### ISSUE TITLE
Order columns by original ordering

### ISSUE THREAD

**Issue by james-langbein** [ernstc/SqlDataInspector#21]
Thanks for this wonderful tool, this is really useful!

Columns are not ordered alphabetically in a SQL Server database. Normally the primary key will be first, then the most important columns etc.

Can you please allow us to order the columns by the original ordering?

This would apply to the Columns and Rows views.

**Comment by Tix2garr** [comment]
I was just coming here to request the same thing!

Through settings would be good.  Even better have something in settings to _default_ order by name or ordinal position, and also have the ability to change it on the Data Inspector tab itself.

If going by ordinal position, obviously will need it as a column as well.

AND....  I _also_ agree that this is a wonderful tool!  Thanks!!  :-)

**Comment by ernstc** [comment]
@james-langbein , @Tix2garr thanks for your feedback. Very appreciated!

The latest release includes the settings for columns ordering and the feature for ordering columns also from the columns view. 
The default behaviour has been changed for using the ordinal ordering for columns. 

I hope this will be helpful for you and don't forget to give a ⭐ if you like it!

Thanks.
Ernesto

**Comment by Tix2garr** [comment]
Woo-hoo!!  Thanks Ernesto!  That's working really well.

I _just_ discovered this extension recently and am really happy I found it, since I am part of doing conversions and it is a very nice tool to help find connections, etc. with the data.  :-)

Once again, well done Ernesto!  :-)

Michael
