### ISSUE TITLE
Request:  Be able to adjust height of results window

### ISSUE THREAD

**Issue by Tix2garr** [ernstc/SqlDataInspector#27]
This is the last one for the day, I promise.  <chuckle>

Many times, for me anyway, I would like to be able to make the results window taller and shrink the upper windows some.  Other times, the table has a _horrendous_ number of columns and/or distinct values and it would be nice to have the upper half of the tab have more room to scroll through the columns/distinct values.

Hope my description makes sense.   :-)

Once again, **thank you** for your work and extension!!

Michael

**Comment by ernstc** [comment]
Thank you for this feature request. It will be considered in a future release. 👍

**Comment by ernstc** [comment]
Hi @Tix2garr,
this feature has been implemented into version 0.8.1: https://github.com/ernstc/SqlDataInspector/releases/tag/0.8.1

**Comment by Tix2garr** [comment]
Woo-hoo!!  Thanks much!!  :-)
