### ISSUE TITLE
Add count of each distinct value and indicate unique values

### ISSUE THREAD

**Issue by jwk6** [ernstc/SqlDataInspector#3]
Add the count of each distinct value, and the number of unique values.  Unique values are those values that appear only once.

Distinct Values (3)
Value | Count | Unique
------------ | ------------- | -------------
A | 10 | 
B | 4 | 
C | 1 | ✔

**Comment by ernstc** [comment]
Maybe the Unique column is not necessary since the Count=1 tells the same info.

**Comment by jwk6** [comment]
True. The inspiration for this is/was the Column Profile view in the Power Query editor of Power BI Desktop.

![image](https://user-images.githubusercontent.com/20860172/119426467-4bc31a00-bcd7-11eb-9c81-10b5c891c866.png)

**Comment by jwk6** [comment]
The column distribution view is pretty cool too.
![image](https://user-images.githubusercontent.com/20860172/119426599-84fb8a00-bcd7-11eb-8a70-9a234671d756.png)

**Comment by ernstc** [comment]
The count of the value occorrences has been added with the [release 0.3.0](https://github.com/ernstc/SqlDataInspector/releases/tag/0.3.0)

**Comment by jwk6** [comment]
Nice! I'll update and try it.

**Comment by jwk6** [comment]
Seems to be working great. Thank you!
