### ISSUE TITLE
SqlDataInspector connects to the user's default database, rather than selected database

### ISSUE THREAD

**Issue by yuhawlim** [ernstc/SqlDataInspector#4]
I have 2 local SQL databases. When I use "Inpsect data" on the highlighted database, the SqlDataInspector connection uses the default database for the user, rather than the highlighted database.

**Comment by AyadShammout** [comment]
Inspect data always open same database instead of selected database.

**Comment by ernstc** [comment]
This issue happens when in the connection you have not entered the Database name, so the connection is to a SQL server and not to a specific database. For connections with the Database name it should work correctly.

**Comment by ernstc** [comment]
This bug has been resolved in the [release 0.3.0](https://github.com/ernstc/SqlDataInspector/releases/tag/0.3.0)
