### ISSUE TITLE
Feature Rqst: SqlDataInspector for db "Views" 

### ISSUE THREAD

**Issue by nmystic22** [ernstc/SqlDataInspector#8]
Can SQLDataInspector run on database "Views" as well as "Tables" (with context menu support)??

Would love to see this feature or perhaps identical but new extension if required.

Thanks!

ps. love the current extension for use with db tables: simple, lightning fast way to see some of the most critical aspects of data

**Comment by ernstc** [comment]
This feature is coming in the next release. Thanks for your suggestion.

**Comment by nmystic22** [comment]
Wow! So awesome to have this in the new release. Thank you for adding it @ernstc !!

**Comment by nmystic22** [comment]
> Wow! So awesome to have this in the new release. Thank you for adding it @ernstc !!

HUGE thx for adding functionality for views. Great idea with the checkboxes as well!
